hour1 = int(input())
minute1 = int(input())
second1 = int(input())
hour1 = (hour1 * 60 * 60)
minute1 = (minute1 * 60)
hour2 = int(input())
minute2 = int(input())
second2 = int(input())
hour2 = (hour2 * 60 * 60)
minute2 = (minute2 * 60)
difference = ((hour2 + minute2 + second2) - (hour1 + minute1 + second1))
print(difference)